spring.application.name=authguard

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/authguard-api
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:123456}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.devtools.restart.enabled=false

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.web.resources.add-mappings=false
spring.web.resources.static-locations=classpath:/uploads/

spring.jackson.deserialization.fail-on-unknown-properties=true
spring.jackson.deserialization.fail-on-ignored-properties=true

api.security.token.secret=${API_KEY_SECRET}

socket-server.host=
socket-server.port=

#Logging
logging.file.name=./log/email-service.log
logging.logback.rollingpolicy.file-name-pattern=/log/email-service-%d{yyyy-MM-dd}.%i.log
logging.logback.rollingpolicy.max-file-size=1MB
logging.logback.rollingpolicy.max-history=30
logging.level.org.hibernate=DEBUG

#TOTP
totp.secret.length=128
totp.code.length=8
totp.time.period=15
totp.time.discrepancy=2

google.client.id=${GOOGLE_CLIENT_ID}
resend.api.key=${RESEND_API_KEY}

app.base.url.validation=http://localhost:8080/login/ott