spring.application.name=authguard

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/authguard-api
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver
spring.devtools.restart.enabled=false


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.web.resources.add-mappings=false
spring.web.resources.static-locations=classpath:/uploads/


spring.jackson.deserialization.fail-on-unknown-properties=true
spring.jackson.deserialization.fail-on-ignored-properties=true

socket-server.host=
socket-server.port=

#Logging
logging.file.name=./log/email-service.log
logging.logback.rollingpolicy.file-name-pattern=email-service-%d{yyyy-MM-dd}.%i.log
logging.logback.rollingpolicy.max-file-size=1MB
logging.logback.rollingpolicy.max-history=30
logging.level.org.hibernate=DEBUG
