-- V1__Initial_schema.sql
CREATE TABLE USER_DATA (
    USER_ID SERIAL PRIMARY KEY,
    USER_USERNAME VARCHAR(255) NOT NULL UNIQUE,
    USER_PASSWORD VARCHAR(255),
    USER_EMAIL VARCHAR(255) NOT NULL UNIQUE,
    USER_REGISTER_DATA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    USER_UPDATE_DATA TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE TOTP_SECRET (
    USER_ID BIGINT PRIMARY KEY,
    SECRET_HASH VARCHAR(255) NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USER_DATA(USER_ID)
);

